### ISSUE TITLE
Changes to jscad-text

### ISSUE THREAD

**Issue by z3dev** [r-bt/jscad-text-experiments#1]
@r-bt These are nice changes to the jscad-text package. Why not raise a merge request to the original repository?

**Comment by r-bt** [comment]
Sure, before submitting a merge request, what would you consider accepting? I removed the `loadFont.js` and `loadOpentype.js` files in favour of having the end user directly interact with the OpenType package

**Comment by z3dev** [comment]
@r-bt Very good question. Looking at the loadOpentype.js, I would say this could be dropped, but there should be some documentation on how to use the opentype package in NODE and in BROWSER

Not sure about loadFont. It seems useful for first time users of opentype. Hmm..

**Comment by r-bt** [comment]
Submitted a PR at: https://github.com/jscad-community/jscad-text/pull/7
